[package]
name = "oxide-updater-linux"
version = "1.3.4"
description = "Oxide Editor Linux AppImage update helper"
edition = "2021"

[[bin]]
name = "oxide-updater"
path = "src/main.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
zip = { version = "2.4", default-features = false, features = ["deflate"] }
